export const REQUEST_INIT = 'REQUEST_INIT';
export const REQUEST_FAIL = 'REQUEST_FAIL';

export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
